# Generated by Django 4.1.3 on 2023-03-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='newuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
