# Generated by Django 4.1.3 on 2023-03-29 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofiles_profile_pic_newuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
